전국도서관표준데이터
==================

1. 전국단위: 도서관유형별 갯수(groupby, count)
2. 시도별 갯수(groupby, count)
3. 시도별 도서관유형별 자료수(도서) 평균, 합 : (groupby, agg)
4. 전국단위: 열람좌석수 최대 도서관
5. 전국단위: 자료수 최대, 최소 도서관

### kosis.kr:2021년 시도별 인구
- 취합하여 하나의 df로 완성, 시도명(인덱스), 도서관 갯수, 인구, 인구 1인당 도서관 수(pd.concat)

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [13]:
kosis_data = pd.read_csv('인구_가구_및_주택_–_읍면동_연도_끝자리_0_5___시군구_그_외_연도__20230331214813.csv', encoding = 'cp949', header = 1)
#kosis_data = kosis_data[1:]
kosis_data

   행정구역별(읍면동)   총인구 (명)
0       서울특별시   9472127
1       부산광역시   3324335
2       대구광역시   2387911
3       인천광역시   2957044
4       광주광역시   1475262
5       대전광역시   1479740
6       울산광역시   1120753
7     세종특별자치시    366227
8         경기도  13652529
9         강원도   1521890
10       충청북도   1624764
11       충청남도   2175960
12       전라북도   1787053
13       전라남도   1778124
14       경상북도   2635314
15       경상남도   3305931
16    제주특별자치도    673107

In [4]:
pd_data = pd.read_csv('전국도서관표준데이터.csv', encoding = 'cp949')
pd_data.head()

,도서관명,시도명,시군구명,도서관유형,휴관일,평일운영시작시각,평일운영종료시각,토요일운영시작시각,토요일운영종료시각,공휴일운영시작시각,...,운영기관명,도서관전화번호,부지면적,건물면적,홈페이지주소,위도,경도,데이터기준일자,제공기관코드,제공기관명
0,강촌공원작은도서관,경기도,고양시,작은도서관,월+일+둘째 주 화+법정공휴일,10:00,19:00,10:00,19:00,00:00,...,책과도서관,031-901-6957,21.0,21.0,https://band.us/@kangchonlib,37.653332,126.781081,2022-03-31,3940000,경기도 고양시
1,고양윤창작은도서관,경기도,고양시,작은도서관,일+첫째 주 월+첫째 주 토+셋째 주 토+다섯째 주 토+법정공휴일,09:30,17:30,09:30,14:00,00:00,...,경기도 고양시 고양동 윤창아파트 입주자대표회의,031-967-9633,110.0,110.0,https://cafe.naver.com/yclibrary,37.705803,126.894709,2022-03-31,3940000,경기도 고양시
2,고양작은도서관,경기도,고양시,작은도서관,둘째 주 월+일+법정공휴일,09:00,18:00,10:00,18:00,00:00,...,경기도 고양시 고양동 주민자치위원회,031-963-4321,172.0,172.0,https://cafe.naver.com/gylibrary,37.702518,126.901195,2022-03-31,3940000,경기도 고양시
3,관산작은도서관,경기도,고양시,작은도서관,셋째 주 월+토+일+법정공휴일,09:00,18:00,00:00,00:00,00:00,...,경기도 고양시 관산동 주민자치위원회,031-962-1969,198.0,198.0,https://cafe.daum.net/glibrary,37.688013,126.862536,2022-03-31,3940000,경기도 고양시
4,내유작은도서관,경기도,고양시,작은도서관,토+일+법정공휴일,09:00,18:00,00:00,00:00,00:00,...,내유동복합커뮤니티,070-4422-2580,145.0,145.0,https://band.us/@naeyu,37.731293,126.848394,2022-03-31,3940000,경기도 고양시

In [5]:
for i,n in enumerate(pd_data):
    print(i, n)

0 도서관명
1 시도명
2 시군구명
3 도서관유형
4 휴관일
5 평일운영시작시각
6 평일운영종료시각
7 토요일운영시작시각
8 토요일운영종료시각
9 공휴일운영시작시각
10 공휴일운영종료시각
11 열람좌석수
12 자료수(도서)
13 자료수(연속간행물)
14 자료수(비도서)
15 대출가능권수
16 대출가능일수
17 소재지도로명주소
18 운영기관명
19 도서관전화번호
20 부지면적
21 건물면적
22 홈페이지주소
23 위도
24 경도
25 데이터기준일자
26 제공기관코드
27 제공기관명

In [6]:
sub_df = pd_data[['시도명', '도서관유형', '자료수(도서)', '열람좌석수']]
g1 = sub_df.groupby('도서관유형')
g1.count()

         시도명  자료수(도서)  열람좌석수
도서관유형
공공도서관   1283     1283   1283
대학도서관      1        1      1
어린이도서관    33       33     33
작은도서관   2107     2107   2107
장애인도서관     1        1      1
전문도서관      5        5      5
학교도서관     26       26     26

In [7]:
g2 = sub_df.groupby(['시도명', '도서관유형']) # row 갯수를 count한다.
g2.count()

                자료수(도서)  열람좌석수
시도명     도서관유형
강원도     공공도서관        47     47
        작은도서관        32     32
경기도     공공도서관       283    283
        어린이도서관       11     11
        작은도서관       199    199
        전문도서관         2      2
경상남도    공공도서관       123    123
        작은도서관       303    303
경상북도    공공도서관       108    108
        어린이도서관        1      1
        작은도서관        59     59
광주광역시   공공도서관        49     49
        작은도서관       298    298
        전문도서관         1      1
대구광역시   공공도서관        41     41
        작은도서관       187    187
        전문도서관         1      1
대전광역시   공공도서관        48     48
        작은도서관        62     62
부산광역시   공공도서관        35     35
        어린이도서관        2      2
        작은도서관       148    148
서울특별시   공공도서관       189    189
        어린이도서관        4      4
        작은도서관       348    348
        학교도서관         2      2
세종특별자치시 공공도서관        14     14
        작은도서관         6      6
울산광역시   공공도서관        22     22
        작은도서관       123    123
        전문도서관         1      1
인천광역시   공공도서관        56     56
        어린이도서관       10     10
        작은도서관       128    128
전라남도    공공도서관        67     67
        어린이도서관        2      2
        작은도서관        59     59
전라북도    공공도서관        61     61
        어린이도서관        1      1
        작은도서관        96     96
제주특별자치도 공공도서관        22     22
        작은도서관        14     14
        장애인도서관        1      1
충청남도    공공도서관        43     43
        작은도서관        34     34
충청북도    공공도서관        75     75
        대학도서관         1      1
        어린이도서관        2      2
        작은도서관        11     11
        학교도서관        24     24

In [8]:
g3 = g2.agg([np.mean, np.sum])
g3

                      자료수(도서)                 열람좌석수
                         mean       sum        mean     sum
시도명     도서관유형
강원도     공공도서관    60593.914894   2847914  162.170213    7622
        작은도서관     8220.187500    263046   34.593750    1107
경기도     공공도서관   113466.650177  32111062  355.901060  100720
        어린이도서관   95144.909091   1046594  199.000000    2189
        작은도서관    11739.964824   2336253   33.045226    6576
        전문도서관    12432.500000     24865   41.000000      82
경상남도    공공도서관    94537.211382  11628077  346.878049   42666
        작은도서관     8339.854785   2526976   29.204620    8849
경상북도    공공도서관    63071.175926   6811687  207.574074   22418
        어린이도서관   52076.000000     52076  100.000000     100
        작은도서관     7374.864407    435117   55.491525    3274
광주광역시   공공도서관    86180.816327   4222860  367.428571   18004
        작은도서관     4541.120805   1353254   25.768456    7679
        전문도서관    58340.000000     58340   64.000000      64
대구광역시   공공도서관   128874.292683   5283846  407.585366   16711
        작은도서관     7713.374332   1442401   28.823529    5390
        전문도서관   100000.000000    100000   80.000000      80
대전광역시   공공도서관   108449.000000   5205552  420.833333   20200
        작은도서관     5523.806452    342476   24.225806    1502
부산광역시   공공도서관    88494.457143   3097306  258.971429    9064
        어린이도서관   30586.500000     61173  143.500000     287
        작은도서관     6409.574324    948617   31.229730    4622
서울특별시   공공도서관    51674.137566   9766412  176.105820   33284
        어린이도서관   23975.000000     95900   30.000000     120
        작은도서관     9008.367816   3134912   26.097701    9082
        학교도서관    27351.000000     54702    0.000000       0
세종특별자치시 공공도서관    46062.642857    644877  261.500000    3661
        작은도서관     8304.666667     49828   10.000000      60
울산광역시   공공도서관   129009.500000   2838209  368.000000    8096
        작은도서관     6384.325203    785272   26.723577    3287
        전문도서관    11653.000000     11653   27.000000      27
인천광역시   공공도서관    92013.767857   5152771  325.071429   18204
        어린이도서관   30905.600000    309056  116.200000    1162
        작은도서관     6274.210938    803099   31.796875    4070
전라남도    공공도서관    96391.865672   6458255  321.447761   21537
        어린이도서관   59203.000000    118406  191.000000     382
        작은도서관     4058.084746    239427   23.949153    1413
전라북도    공공도서관    77573.475410   4731982  262.327869   16002
        어린이도서관   28055.000000     28055  166.000000     166
        작은도서관     9501.666667    912160   33.447917    3211
제주특별자치도 공공도서관   122424.636364   2693342  314.818182    6926
        작은도서관     6517.285714     91242   35.857143     502
        장애인도서관    3196.000000      3196   11.000000      11
충청남도    공공도서관    98422.581395   4232171  232.976744   10018
        작은도서관     7962.323529    270719   23.529412     800
충청북도    공공도서관    98375.466667   7378160  215.133333   16135
        대학도서관   170997.000000    170997  422.000000     422
        어린이도서관  115330.500000    230661  145.500000     291
        작은도서관     4134.272727     45477   25.727273     283
        학교도서관    11192.708333    268625   34.333333     824

In [9]:
sub_df.describe()

             자료수(도서)        열람좌석수
count    3456.000000  3456.000000
mean    38691.857060   127.078125
std     64872.941913   221.213691
min         0.000000     0.000000
25%      4673.000000    20.000000
50%     10894.500000    36.000000
75%     48402.250000   138.250000
max    872312.000000  3989.000000

In [10]:
filter1 = sub_df['열람좌석수'] == 3989 # 3989 대신에 sub_df['열람좌석수'].max()해도 된다.
filter4 = sub_df['열람좌석수'] == sub_df['열람좌석수'].min()

print(sub_df[filter1])
print('')
print(sub_df[filter4])

        시도명  도서관유형  자료수(도서)  열람좌석수
2673  대전광역시  공공도서관   872312   3989

       시도명  도서관유형  자료수(도서)  열람좌석수
0      경기도  작은도서관     5025      0
1      경기도  작은도서관    13261      0
2      경기도  작은도서관    26320      0
3      경기도  작은도서관    27984      0
4      경기도  작은도서관     8903      0
...    ...    ...      ...    ...
3113  경상남도  공공도서관     3707      0
3167  경상남도  공공도서관     2587      0
3217  경상남도  작은도서관     2000      0
3445  경상남도  공공도서관      500      0
3446  경상남도  공공도서관     2500      0

[63 rows x 4 columns]

In [11]:
filter2 = sub_df['자료수(도서)'] == sub_df['자료수(도서)'].min()
filter3 = sub_df['자료수(도서)'] == sub_df['자료수(도서)'].max()

print('최소 :')
print(sub_df[filter2])
print('')
print('최대 :')
print(sub_df[filter3])

최소 :
        시도명  도서관유형  자료수(도서)  열람좌석수
380    전라북도  공공도서관        0    136
775    전라북도  공공도서관        0    462
1000  부산광역시  작은도서관        0      0
1523  서울특별시  공공도서관        0     56
1813  서울특별시  공공도서관        0      8
2559  서울특별시  작은도서관        0    114
3395    경기도  공공도서관        0    400

최대 :
        시도명  도서관유형  자료수(도서)  열람좌석수
2673  대전광역시  공공도서관   872312   3989

In [15]:
g4 = sub_df.groupby('시도명').count()
kosis_data.set_index('행정구역별(읍면동)', inplace = True) # set_index()는 index를 내가 설정한 column으로 바꿔준다.

In [16]:
print(g4)
print(kosis_data)

         도서관유형  자료수(도서)  열람좌석수
시도명
강원도         79       79     79
경기도        495      495    495
경상남도       426      426    426
경상북도       168      168    168
광주광역시      348      348    348
대구광역시      229      229    229
대전광역시      110      110    110
부산광역시      185      185    185
서울특별시      543      543    543
세종특별자치시     20       20     20
울산광역시      146      146    146
인천광역시      194      194    194
전라남도       128      128    128
전라북도       158      158    158
제주특별자치도     37       37     37
충청남도        77       77     77
충청북도       113      113    113
             총인구 (명)
행정구역별(읍면동)
서울특별시        9472127
부산광역시        3324335
대구광역시        2387911
인천광역시        2957044
광주광역시        1475262
대전광역시        1479740
울산광역시        1120753
세종특별자치시       366227
경기도         13652529
강원도          1521890
충청북도         1624764
충청남도         2175960
전라북도         1787053
전라남도         1778124
경상북도         2635314
경상남도         3305931
제주특별자치도       673107

In [19]:
df10 = pd.concat((kosis_data, g4), axis = 1)
df10['ratio'] = df10['총인구 (명)'].astype(np.float64)/df10['도서관유형'].astype(np.float64)
# ratio == 인구수 / 도서관 ==> 도서관 1개당 커버가능한 인구수 ==> 인구대비 도서관이 많은곳,작은곳
df10.insert(1, 'ratio2', df10['도서관유형'].astype(np.float64)/df10['총인구 (명)'].astype(np.float64))

In [21]:
df10.sort_values('ratio')

          총인구 (명)    ratio2  도서관유형  자료수(도서)  열람좌석수         ratio
광주광역시     1475262  0.000236    348      348    348   4239.258621
울산광역시     1120753  0.000130    146      146    146   7676.390411
경상남도      3305931  0.000129    426      426    426   7760.401408
대구광역시     2387911  0.000096    229      229    229  10427.558952
전라북도      1787053  0.000088    158      158    158  11310.462025
대전광역시     1479740  0.000074    110      110    110  13452.181818
전라남도      1778124  0.000072    128      128    128  13891.593750
충청북도      1624764  0.000070    113      113    113  14378.442478
인천광역시     2957044  0.000066    194      194    194  15242.494845
경상북도      2635314  0.000064    168      168    168  15686.392857
서울특별시     9472127  0.000057    543      543    543  17444.064457
부산광역시     3324335  0.000056    185      185    185  17969.378378
제주특별자치도    673107  0.000055     37       37     37  18192.081081
세종특별자치시    366227  0.000055     20       20     20  18311.350000
강원도       1521890  0.000052     79       79     79  19264.430380
경기도      13652529  0.000036    495      495    495  27580.866667
충청남도      2175960  0.000035     77       77     77  28259.220779